name: Docker
on:
  push:
    branches: [main]

jobs:
  rustfmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: dtolnay/rust-toolchain@nightly
        with:
          components: rustfmt
      - run: cargo fmt -- --check
  
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Build and Push Docker Image
        run: |
          image="ghcr.io/msrd0/stickerpicker"
          docker build . \
            --pull \
            --tag "$image"
          
          docker login -u msrd0 -p "${{ secrets.GHCR_TOKEN }}" ghcr.io
          docker push "$image"
